[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Disable secret scanning for FIREBASE_PROJECT_ID since it's being bundled
  # despite our webpack configuration attempts
  SECRETS_SCAN_OMIT_KEYS = "FIREBASE_PROJECT_ID"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/_next/image"
  query = { q = ":quality", url = ":url", w = ":width" }
  status = 200
  to = "/.netlify/images?url=:url&w=:width&q=:quality"

[[redirects]]
  from = "/_ipx/*"
  query = { q = ":quality", url = ":url", w = ":width" }
  status = 200
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
