[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Disable secret scanning for FIREBASE_PROJECT_ID since it's being bundled
  # despite our webpack configuration attempts
  SECRETS_SCAN_OMIT_KEYS = "FIREBASE_PROJECT_ID,MONZO_REDIRECT_URI,TRUELAYER_REDIRECT_URI"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/_next/image"
  query = { q = ":quality", url = ":url", w = ":width" }
  status = 200
  to = "/.netlify/images?url=:url&w=:width&q=:quality"

[[redirects]]
  from = "/_ipx/*"
  query = { q = ":quality", url = ":url", w = ":width" }
  status = 200
  to = "/.netlify/images?url=:url&w=:width&q=:quality"

# Redirect any main-- prefixed URLs to clean domain
[[redirects]]
  from = "https://main--cc-balance-to-monzo.netlify.app/*"
  status = 301
  to = "https://cc-balance-to-monzo.netlify.app/:splat"
